# Generated by Django 3.2.2 on 2021-06-11 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ITSPfrontend', '0018_auto_20210610_1445'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Info',
            new_name='Information',
        ),
    ]
